---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: ansible.posix
      - name: ansible.windows
      - name: awx.awx
      - name: azure.azcollection
        version: ">=2.1.0"
      - name: amazon.aws
      - name: community.general
      - name: community.docker
      - name: community.vmware
      - name: google.cloud
      - name: kubernetes.core
      - name: kubevirt.core
      - name: ovirt.ovirt
      - name: openstack.cloud
      - name: redhatinsights.insights
      - name: theforeman.foreman
  system: |
    git-core [platform:rpm]
    python3.11-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    cmake [platform:rpm compile]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    make [platform:rpm compile]
    openssl-devel [platform:rpm compile]
  python: |
    git+https://github.com/ansible/ansible-sign
    docker
    kubernetes
    jinja2
    jmespath
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl
additional_build_steps:
  prepend_base:
    - RUN yum install -y python3.11 unzip tar wget sudo && \
    - mkdir -p "/opt/intel/intel_certs" && \
    - curl --noproxy ".intel.com" -O -L "http://certificates.intel.com/repository/certificates/Intel%20Root%20Certificate%20Chain%20Base64.zip" --output-dir "/opt/intel/intel_certs" && \
    - curl --noproxy ".intel.com" -O -L "http://certificates.intel.com/repository/certificates/PublicSHA2RootChain-Base64-crosssigned.zip" --output-dir "/opt/intel/intel_certs" && \
    - curl --noproxy ".intel.com" -O -L "http://certificates.intel.com/repository/certificates/IntelSHA2RootChain-Base64.zip" --output-dir "/opt/intel/intel_certs" && \
    - unzip "/opt/intel/intel_certs/"\*.zip -d /usr/local/share/ca-certificates && \
    - update-ca-trust
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    # SymLink `python` -> `python3.11`
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 311
